### ISSUE TITLE
If the length of the token exceeds 10, there is a problem with the length

### ISSUE THREAD

**Issue by WENGSYX** [google-deepmind/tracr#7]
```
def make_length(sop):
  all_true_selector = rasp.Select(sop, sop, rasp.Comparison.TRUE)
  return rasp.SelectorWidth(all_true_selector)

model = compiling.compile_rasp_to_model(
    make_length,
    vocab={1, 2, 3},
    max_seq_len=12,
    compiler_bos=bos,
)

print(model.apply([bos, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2]).decoded)
>>> ['BOS', 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10]
```

But in fact, there are 11 tokens。

**Comment by david-lindner** [comment]
This seems to be an issue with the accuracy of the MLP layer inside the SelectorWidth operation. Can you try adding the argument `mlp_exactness=1000` to the compiling step? This should make the MLP more accurate and avoid this issue.

**Comment by david-lindner** [comment]
This should be fixed by https://github.com/google-deepmind/tracr/commit/732606d976ff2b1cbbb190c5edea7774456a8de2
